env: "local"
http_server:
  address: "localhost:8003"
  timeout: 4s
  idle_timeout: 60s
postgres_storage:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: 1423
  dbname: "airbnb_apartment"